### ISSUE TITLE
dont work on linux 

### ISSUE THREAD

**Issue by LeoCaprile** [Dteyn/SF2000_BGM_Tool#1]
sad face

**Comment by Dteyn** [comment]
Sorry for the late reply but figured better late than never haha :)

I just posted an update v0.2.0 which should now work on Linux. I tested it on Linux Mint and it's working well for me. Check out the main page here for details: https://github.com/Dteyn/SF2000_BGM_Tool

If you run into any issues just let me know!

**Comment by LeoCaprile** [comment]
> Sorry for the late reply but figured better late than never haha :)
> 
> I just posted an update v0.2.0 which should now work on Linux. I tested it on Linux Mint and it's working well for me. Check out the main page here for details: https://github.com/Dteyn/SF2000_BGM_Tool
> 
> If you run into any issues just let me know!

Wow Thanks!! I tested and it worked !!
